spring:  
  application:
    name: gateway-server

server:
  port: 8762   
        
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
           
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:4010/authentication-service/oauth
    complain-service:
      path: /complain-service/**
      url: http://localhost:4011
      
ribbon:
    eager-load:
      enabled: true
      
      
